[author.Anonymous]
same_as = ["https://en.wikipedia.org/wiki/Anonymous_work", "https://www.wikidata.org/wiki/Q4233718"]
[author.Demosthenes]
same_as = ["https://en.wikipedia.org/wiki/Demosthenes", "https://www.wikidata.org/wiki/Q117253"]

[period.classical-greece]
"wikidata" = "https://www.wikidata.org/wiki/Q843745"
